Laba45Tsi/Controllers/filmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Laba45Tsi.Managers.filmManager;
using Laba45Tsi.Storage.Entity;
using Microsoft.AspNetCore.Mvc;

namespace Laba45Tsi.Controllers
{
    public class filmController : Controller
    {
        private readonly iFilmManager _filmManager;

        public filmController(iFilmManager Manager)
        {
            _filmManager = Manager;
        }

        [HttpGet]
        public async Task<ViewResult> showFilmByGenre(Guid id)
        {
            var entity = await _filmManager.getAllByGenre(id);

            genreEntity genre = _filmManager.getGenreById(id);

            ViewBag.genre = genre;

            ViewBag.id = genre.id;

            return View(entity);
        }

        [HttpGet]
        public async Task<ViewResult> showFilmByProducer(Guid id)
        {
            var entity = await _filmManager.getAllByProducer(id);

            producerEntity producer = _filmManager.getProducerById(id);

            ViewBag.producer = producer;

            ViewBag.id = producer.id;

            return View(entity);
        }
        [HttpGet]
        public ViewResult addFilmByGenre(Guid id)
        {
            genreEntity genre = _filmManager.getGenreById(id);

            ViewBag.genre = genre;

            return View();
        }

        [HttpGet]
        public ViewResult addFilmByProducer(Guid id)
        {
            producerEntity producer = _filmManager.getProducerById(id);

            ViewBag.producer = producer;

            return View();
        }

        public async Task<ActionResult> addByGenre(filmCreatOrUpdateRequest request)
        {
            var item = await _filmManager.getProducerByName(request.producerName);

            if (item != null)
            {
                request.producerId = item.id;
            }
            else 
            {
                item = await _filmManager.addProducerEntity(request.producerName);
                request.producerId = item.id;
            }
            
            await _filmManager.addFilmEntity(request);

            return Redirect("/film/showFilmByGenre/" + request.genreId);
        }

        public async Task<ActionResult> addByProducer(filmCreatOrUpdateRequest request)
        {
            var item = await _filmManager.getGenreByName(request.genreName);

            if (item != null)
            {
                request.genreId = item.id;
            }
            else
            {
                item = await _filmManager.addGenreEntity(request.genreName);
                request.genreId = item.id;
            }

            await _filmManager.addFilmEntity(request);

            return Redirect("/film/showFilmByProducer/" + request.producerId);
        }

        [HttpGet]
        public async Task<ActionResult> dellByGenre(Guid id)
        {
            var genreId = _filmManager.getFilmById(id).genreId;

            await _filmManager.dellFilmEntity(id);

            return Redirect("/film/showFilmByGenre/" + genreId);
        }

        [HttpGet]
        public async Task<ActionResult> dellByProducer(Guid id)
        {
            var producerId = _filmManager.getFilmById(id).producerId;

            await _filmManager.dellFilmEntity(id);

            return Redirect("/film/showFilmByProducer/" + producerId);
        }

        [HttpGet]
        public ViewResult updateFilmByGenre(Guid id)
        {

            var entity = _filmManager.getFilmById(id);

            return View(entity);
        }

        [HttpGet]
        public ViewResult updateFilmByProducer(Guid id)
        {
            var entity = _filmManager.getFilmById(id);

            ViewBag.producerId = entity.producerId;

            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> updateByGenre(Guid id, filmCreatOrUpdateRequest request)
        {
            var item = await _filmManager.getProducerByName(request.producerName);

            if (item != null)
            {
                request.producerId = item.id;
            }
            else
            {
                item = await _filmManager.addProducerEntity(request.producerName);
                request.producerId = item.id;
            }

            await _filmManager.updateFilm(id, request);

            return Redirect("/film/showFilmByGenre/" + request.genreId);
        }

        [HttpPost]
        public async Task<ActionResult> updateByProducer(Guid id, filmCreatOrUpdateRequest request)
        {
            var item = await _filmManager.getGenreByName(request.genreName);

            if (item != null)
            {
                request.genreId = item.id;
            }
            else
            {
                item = await _filmManager.addGenreEntity(request.genreName);
                request.genreId = item.id;
            }

            await _filmManager.updateFilm(id, request);

            return Redirect("/film/showFilmByProducer/" + request.producerId);
        }
    }
}

Laba45Tsi/Controllers/genreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Laba45Tsi.Managers.genreManager;
using Microsoft.AspNetCore.Mvc;

namespace Laba45Tsi.Controllers
{
    public class genreController : Controller
    {
        private readonly iGenreManager _genreManager;

        public genreController(iGenreManager Manager)
        {
            _genreManager = Manager;
        }

        [HttpGet]
        public async Task<ViewResult> showGenre()
        {
            var entity = await _genreManager.getAll();

            return View(entity);
        }

        public ViewResult addGenre()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> add(string request)
        {
            await _genreManager.addGenreEntity(request);

            return RedirectToAction(nameof(showGenre));
        }

        [HttpGet]
        public async Task<ViewResult> updateGenre(Guid id)
        {
            var entity = await _genreManager.getById(id);

            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> update(Guid id, string request)
        {
            await _genreManager.updateGenre(id, request);

            return RedirectToAction(nameof(showGenre));
        }

        [HttpGet]
        public async Task<ActionResult> dell(Guid id)
        {
            await _genreManager.dellGenreEntity(id);

            return RedirectToAction(nameof(showGenre));
        }
    }
}

Laba45Tsi/Controllers/producerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Laba45Tsi.Managers.producerManager;
using Microsoft.AspNetCore.Mvc;

namespace Laba45Tsi.Controllers
{
    public class producerController : Controller
    {
        private readonly iProducerManager _producerManager;

        public producerController(iProducerManager Manager)
        {
            _producerManager = Manager;
        }

        [HttpGet]
        public async Task<ViewResult> showProducer()
        {
            var entity = await _producerManager.getAll();

            return View(entity);
        }

        public ViewResult addProducer()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> add(string request)
        {
            await _producerManager.addProducerEntity(request);

            return RedirectToAction(nameof(showProducer));
        }

        [HttpGet]
        public async Task<ViewResult> updateProducer(Guid id)
        {
            var entity = await _producerManager.getById(id);

            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> update(Guid id, string request)
        {
            await _producerManager.updateProduser(id, request);

            return RedirectToAction(nameof(showProducer));
        }

        [HttpGet]
        public async Task<ActionResult> Dell(Guid id)
        {
            await _producerManager.dellProducerEntity(id);

            return RedirectToAction(nameof(showProducer));
        }
    }
}

Laba45Tsi/Views/film/addFilmByGenre.cshtml
@model Laba45Tsi.Managers.filmManager.filmCreatOrUpdateRequest
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddClient</title>
</head>
<body>
    @using (Html.BeginForm("addByGenre", "film", FormMethod.Post))
    {
        <label>Жанр : @ViewBag.genre.genreName</label>
        <input type="hidden" value="@ViewBag.genre.id" name="genreId">
        <input type="hidden" value="@ViewBag.genre.genreName" name="genreName"><br /><br />

        <label>Название фильма : </label>
        <input type="text" id="filmName" name="filmName" /><br /><br />
        <label>Фамилия и имя режисера : </label>
        <input type="text" id="producerName" name="producerName">

        <input type="submit" value="Содать">
    }
    <a href="/film/showFilmByGenre/@ViewBag.genre.id">Вернуться</a>
</body>
</html>

Laba45Tsi/Views/film/addFilmByProducer.cshtml
@model Laba45Tsi.Managers.filmManager.filmCreatOrUpdateRequest
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddClient</title>
</head>
<body>
    @using (Html.BeginForm("addByProducer", "film", FormMethod.Post))
    {
        <label>Режисер : @ViewBag.producer.name</label>
        <input type="hidden" value="@ViewBag.producer.id" name="producerId">
        <input type="hidden" value="@ViewBag.producer.name" name="producerName"><br /><br />

        <label>Название фильма : </label>
        <input type="text" id="filmName" name="filmName" /><br /><br />
        <label>Жанр : </label>
        <input type="text" id="ganreName" name="ganreName">

        <input type="submit" value="Содать">
    }
<a href="/film/showFilmByProducer/@ViewBag.producer.id">Вернуться</a>
</body>
</html>

Laba45Tsi/Views/film/showFilmByGenre.cshtml
@model IEnumerable<Laba45Tsi.Storage.Entity.filmEntity>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowClient</title>
</head>
<body>
    <div>
        <h2>Фильмы жанра @ViewBag.ganre</h2>
        @foreach (var item in Model)
        {
            <label>Название фильма : </label>@item.filmName<br />
            <label>Продюсер : </label>@item.producerName<br />
            <a href="/film/updateFilmByGenre/@item.id">Изменить информацию о фильме</a>
            <a href="/film/dellByGenre/@item.id">Удалить</a>
            <br />
        }
        <a href="/film/addFilmByGenre/@ViewBag.id">Добвить фильм</a><br />
        <a href="https://localhost:44303/">Список жанров</a><br />

    </div>
</body>
</html>

Laba45Tsi/Views/film/showFilmByProducer.cshtml
@model IEnumerable<Laba45Tsi.Storage.Entity.filmEntity>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowClient</title>
</head>
<body>
    <div>
        <h2>Фильмы режисера @ViewBag.producer.name</h2>
        @foreach (var item in Model)
        {
            <label>Название фильма : </label>@item.filmName<br />
            <label>Жанр : </label>@item.genreName<br />
            <a href="/film/updateFilmByProducer/@item.id">Изменить информацию о фильме</a>
            <a href="/film/dellByProducer/@item.id">Удалить</a>
            <br />
        }
        <a href="/film/addFilmByProducer/@ViewBag.id">Добвить фильм</a><br />
        <a href="/producer/showProducer">Список режисёров</a><br />

    </div>
</body>
</html>

Laba45Tsi/Views/film/updateFilmByGenre.cshtml
@model Laba45Tsi.Storage.Entity.filmEntity
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddClient</title>
</head>
<body>
    @using (Html.BeginForm("updateByGenre", "film", FormMethod.Post))
    {
        <label>Жанр : @Model.genreName</label>
        <input type="hidden" value="@Model.genreId" name="genreId">
        <input type="hidden" value="@Model.genreName" name="genreName">

        <label>Название фильма : </label>
        <input type="text" id="filmName" name="filmName" value="@Model.filmName" /><br /><br />


        <label>Фамилия и имя режисера : </label>
        <input type="text" id="producerName" name="producerName" value="@Model.producerName"><br />
        <input type="submit" value="Обновить">
        <input type="hidden" name="id" id="id" value="@Model.id">

    }
<a href="/film/showFilmByGenre/@Model.genreId">Вернуться</a>
</body>
</html>

Laba45Tsi/Views/film/updateFilmByProducer.cshtml
@model Laba45Tsi.Storage.Entity.filmEntity
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddClient</title>
</head>
<body>
    @using (Html.BeginForm("updateByProducer", "film", FormMethod.Post))
    {
        <label>Жанр </label>
        <input type="text" id="genreName" value="@Model.genreName" name="genreName">

        <label>Название фильма : </label>
        <input type="text" id="filmName" name="filmName" value="@Model.filmName" /><br /><br />


        <label>Фамилия и имя режисера @Model.producerName </label>
        <input type="hidden" id="producerName" name="producerName" value="@Model.producerName">
        <input type="hidden" id="producerId" name="producerId" value="@Model.producerId"><br />
        <input type="submit" value="Обновить">
        <input type="hidden" name="id" id="id" value="@Model.id">

    }
    <a href="/film/showFilmByProducer/@Model.producerId">Вернуться</a>
</body>
</html>

Laba45Tsi/Views/genre/addGenre.cshtml
@model string
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddRoom</title>
</head>
<body>
    @using (Html.BeginForm("add", "genre", FormMethod.Post))
    {
        <label>Название жанра : </label>
        <input type="text" id="request" name="request" /><br />

        <input type="submit" value="Добавить жанр">
    }
<a href="/genre/showGenre">Вернуться</a>
</body>
</html>

Laba45Tsi/Views/genre/showGenre.cshtml
@model IEnumerable<Laba45Tsi.Storage.Entity.genreEntity>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Жанры</title>
</head>
<body>
    <div>
        <h1>Жанры</h1>
        @foreach (var item in Model)
        {
            <label>Название жанра : </label>@item.genreName<br />
            <a href="/genre/updateGenre/@item.id">Редактировать жанр</a>
            <a href="/film/showFilmByGenre/@item.id">Показать фильмы</a>
            <a href="/genre/dell/@item.id">Удалить</a>
            <br />
        }
        @using (Html.BeginForm("addGenre", "genre"))
        {
            <div><input type="submit" value="Добавить жанр"></div>
        }
        <a href="/producer/showProducer">Список режисеров</a>
    </div>
</body>
</html>

Laba45Tsi/Views/genre/updateGenre.cshtml
@model Laba45Tsi.Storage.Entity.genreEntity
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateRoom</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("update", "genre", FormMethod.Post))
        {
            <label>Названеи жанра : </label>
            <input type="text" id="request" name="request" value="@Model.genreName" /><br /><br />
            <input type="hidden" id="id" name="id" value="@Model.id">
            <input type="submit" value="Обновить информацию о номере">
        }
    <a href="/genre/showGenre">Вернуться</a>
    </div>
</body>
</html>

Laba45Tsi/Views/producer/addProducer.cshtml
@model string
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddRoom</title>
</head>
<body>
    @using (Html.BeginForm("add", "producer", FormMethod.Post))
    {
        <label>Имя и фамилия режисера : </label>
        <input type="text" id="request" name="request" /><br />

        <input type="submit" value="Добавить режисера">
    }
    <a href="/producer/showProducer">Вернуться</a>
</body>
</html>

Laba45Tsi/Views/producer/showProducer.cshtml
@model IEnumerable<Laba45Tsi.Storage.Entity.producerEntity>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Режисёры</title>
</head>
<body>
    <div>
        <h1>Режисёры</h1>
        @foreach (var item in Model)
        {
            <label>Фамилия и имя режисера : </label>@item.name<br />
            <a href="/producer/updateProducer/@item.id">Редактировать режисёра</a>
            <a href="/film/showFilmByProducer/@item.id">Показать фильмы</a>
            <a href="/producer/dell/@item.id">Удалить</a>
            <br />
        }
        @using (Html.BeginForm("addProducer", "producer"))
        {
            <div><input type="submit" value="Добавить режисера"></div>
        }
        <a href="/genre/showGenre">Список жанров</a>
    </div>
</body>
</html>

Laba45Tsi/Views/producer/updateProducer.cshtml
@model Laba45Tsi.Storage.Entity.producerEntity
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Обновить информацию о режисере</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("update", "producer", FormMethod.Post))
        {
            <label>Фамилия и имя режисера : </label>
            <input type="text" id="request" name="request" value="@Model.name" /><br /><br />
            <input type="hidden" id="id" name="id" value="@Model.id" />
            <input type="submit" value="Обновить информацию о режисере">
        }
    <a href="/producer/showProducer">Вернуться</a>
    </div>
</body>
</html>